// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// 📦 Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1zfEdgAoGslPoyMnIvbOyq2zxinuSWL0',
    appId: '1:20536898012:web:2d6984d82f508b3ec71f19',
    messagingSenderId: '20536898012',
    projectId: 'blast-player-free',
    authDomain: 'blast-player-free.firebaseapp.com',
    storageBucket: 'blast-player-free.firebasestorage.app',
    measurementId: 'G-PTH2LKCG6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjC2ubmiARDFmLNYP8EnLmLl0IlOsRIjY',
    appId: '1:549887739198:android:aff012d31019fc2926586f',
    messagingSenderId: '549887739198',
    projectId: 'acgn-client',
    storageBucket: 'acgn-client.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLauXdaDlIxSGxRAjg2xONSw4wD9sV6ys',
    appId: '1:549887739198:ios:ad9c8e215c95bcb026586f',
    messagingSenderId: '549887739198',
    projectId: 'acgn-client',
    storageBucket: 'acgn-client.firebasestorage.app',
    iosBundleId: 'com.yehua.player.com',
  );

}