part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const HOME = _Paths.HOME;
  static const SPLASH_PAGE = _Paths.SPLASH_PAGE;
  static const TOPIC_DETAIL_PAGE = _Paths.TOPIC_DETAIL_PAGE;
  static const HOME_INDEX_WEB = _Paths.HOME + _Paths.HOME_INDEX_WEB;
  static const HOME_POST_CENTER = _Paths.HOME + _Paths.HOME_POST_CENTER;
  static const HOME_MINE_CENTER = _Paths.HOME + _Paths.HOME_MINE_CENTER;
  static const REDEEM_CODE_PAGE = _Paths.REDEEM_CODE_PAGE;

  static const HOME_RECOMMEND_PAGE = _Paths.HOME_RECOMMEND_PAGE;
  static const HOME_GIFS_PAGE = _Paths.HOME_GIFS_PAGE;
  static const VIP_CENTER_PAGE = _Paths.VIP_CENTER_PAGE;
  static const SETTING_PAGE = _Paths.SETTING_PAGE;
  static const SET_USER_AVATAR_PAGE = _Paths.SET_USER_AVATAR_PAGE;
  static const SET_ACCOUNT_FIND = _Paths.SET_ACCOUNT_FIND;
  static const SCAN_QR_CODE = _Paths.SCAN_QR_CODE;
  static const PHONE_NUMBER = _Paths.PHONE_NUMBER;

  static const SHARE_APP_PAGE = _Paths.SHARE_APP_PAGE;
  static const BIND_MOBILE_PAGE = _Paths.BIND_MOBILE_PAGE;
  static const USER_TERMS_PAGE = _Paths.USER_TERMS_PAGE;
  static const SUB_TERMS_PAGE = _Paths.SUB_TERMS_PAGE;
  static const MINI_DRAMA_PLAYER_PAGE = _Paths.MINI_DRAMA_PLAYER_PAGE;
  static const VPN_LINES_PAGE = _Paths.VPN_LINES_PAGE;
  static const WELFARE_TASK_PAGE = _Paths.WELFARE_TASK_PAGE;
  static const ACTIVITY_CENTER_PAGE = _Paths.ACTIVITY_CENTER_PAGE;
  static const ACTIVITY_WEB_PAGE = _Paths.ACTIVITY_WEB_PAGE;
  static const WEEKLY_CHECK_TASK_PAGE = _Paths.WEEKLY_CHECK_TASK_PAGE;
  static const TICKET_MANAGE_PAGE = _Paths.TICKET_MANAGE_PAGE;
  static const MESSAGE_CENTER_PAGE = _Paths.MESSAGE_CENTER_PAGE;
  static const SYSTEM_MESSAGE_PAGE = _Paths.SYSTEM_MESSAGE_PAGE;
  static const ABOUT_US_PAGE = _Paths.ABOUT_US_PAGE;
  static const CUSTOM_SERVICE_PAGE = _Paths.CUSTOM_SERVICE_PAGE;
  static const BILL_RECORD_PAGE_VIEW = _Paths.BILL_RECORD_PAGE_VIEW;
  static const BILL_RECORD_LIST = _Paths.BILL_RECORD_LIST;
  static const SPEED_TESTING = _Paths.SPEED_TESTING;
  static const VIDEO_PLAYER_PAGE = _Paths.VIDEO_PLAYER_PAGE;
  static const SEARCH_PAGE = _Paths.SEARCH_PAGE;
  static const EVERY_DAY_BEST_PAGE = _Paths.EVERY_DAY_BEST_PAGE;
  static const MINE_COLLECT_PAGE = _Paths.MINE_COLLECT_PAGE;
  static const POST_DETAILE_PAGE = _Paths.POST_DETAILE_PAGE;
  static const POST_TOPIC_PAGE = _Paths.POST_TOPIC_PAGE;
  static const TAG_DETAIL_PAGE = _Paths.TAG_DETAIL_PAGE;
  static const WITHDRAW_CASH_BANK = _Paths.WITHDRAW_CASH_BANK;
  static const BINDING_BANK_CARD = _Paths.BINDING_BANK_CARD;
  static const ENTER_GAME_WEB_VIEW = _Paths.ENTER_GAME_WEB_VIEW;
  static const SHORT_VIDEO_PLAYER = _Paths.SHORT_VIDEO_PLAYER;
  static const INVITED_PAGE = _Paths.INVITED_PAGE;
  static const GAME_DETAILS_PAGE = _Paths.GAME_DETAILS_PAGE;
  static const COMIC_DETAIL_PAGE = _Paths.COMIC_DETAIL_PAGE;
  static const COMIC_READER_PAGE = _Paths.COMIC_READER_PAGE;
  static const NOVEL_DETAIL_PAGE = _Paths.NOVEL_DETAIL_PAGE;
  static const NOVEL_READER_PAGE = _Paths.NOVEL_READER_PAGE;
  static const CATEGORY_DETAIL_PAGE = _Paths.CATEGORY_DETAIL_PAGE;
  static const BOOK_STORE_PAGE = _Paths.BOOK_STORE_PAGE;
  static const RANK_LIST_PAGE = _Paths.RANK_LIST_PAGE;
  static const EPISODE_PREVIEW_PAGE = _Paths.EPISODE_PREVIEW_PAGE;
  static const COMIC_WISHED_PAGE = _Paths.COMIC_WISHED_PAGE;
  static const WISHED_ACTIVE_PAGE = _Paths.WISHED_ACTIVE_PAGE;
  static const WISHING_PAGE = _Paths.WISHING_PAGE;
  static const BOOK_SHELF_PAGE = _Paths.BOOK_SHELF_PAGE;
  static const WATCH_HISTORY_PAGE = _Paths.WATCH_HISTORY_PAGE;
  static const REWARD_HISTORY_PAGE = _Paths.REWARD_HISTORY_PAGE;
  static const AI_CHANGE_FACE_PAGE = _Paths.AI_CHANGE_FACE_PAGE;
  static const AI_TASK_LIST_PAGE = _Paths.AI_TASK_LIST_PAGE;
  static const PREVIEW_IMAGE_VIEWER = _Paths.PREVIEW_IMAGE_VIEWER;
  static const MY_CACHE_PAGE = _Paths.MY_CACHE_PAGE;
  static const AI_RECOMMEND_PAGE = _Paths.AI_RECOMMEND_PAGE;
}

abstract class _Paths {
  _Paths._();

  static const HOME = '/home';
  static const SPLASH_PAGE = '/splash-page';
  static const TOPIC_DETAIL_PAGE = '/topic-detail-page';
  static const HOME_INDEX_WEB = '/home-index-web';
  static const HOME_POST_CENTER = '/home-post-center';
  static const HOME_MINE_CENTER = '/home-mine-center';
  static const REDEEM_CODE_PAGE = '/redeem_code_page';
  static const HOME_RECOMMEND_PAGE = '/home-recommend-page';
  static const HOME_GIFS_PAGE = '/home-gifs-page';
  static const VIP_CENTER_PAGE = '/vip_center_page';
  static const SETTING_PAGE = '/setting-page';
  static const SET_USER_AVATAR_PAGE = '/set_user_avatar_page';
  static const SET_ACCOUNT_FIND = '/set_account_find';
  static const SCAN_QR_CODE = '/scan-qr-code';
  static const PHONE_NUMBER = '/phone-number';
  static const SHARE_APP_PAGE = '/share_invite_page';
  static const BIND_MOBILE_PAGE = '/bind-mobile-page';
  static const USER_TERMS_PAGE = '/user-terms-page';
  static const SUB_TERMS_PAGE = '/sub-terms-page';
  static const MINI_DRAMA_PLAYER_PAGE = '/mini-drama-player-page';
  static const VPN_LINES_PAGE = '/vpn-lines-page';
  static const WELFARE_TASK_PAGE = '/welfare-task-page';
  static const WEEKLY_CHECK_TASK_PAGE = '/weekly_check_task_page';
  static const TICKET_MANAGE_PAGE = '/ticket-manage-page';
  static const MESSAGE_CENTER_PAGE = '/message-center-page';
  static const SYSTEM_MESSAGE_PAGE = '/system-message-page';
  static const ABOUT_US_PAGE = '/about-us-page';
  static const CUSTOM_SERVICE_PAGE = '/custom-service-page';
  static const LOGIN_CENTER = '/login-center';
  static const BILL_RECORD_PAGE_VIEW = '/bill-record-page';
  static const BILL_RECORD_LIST = '/bill-record-list';
  static const SPEED_TESTING = '/speed-testing';
  static const VIDEO_PLAYER_PAGE = '/video-player-page';
  static const SEARCH_PAGE = '/search-page';
  static const EVERY_DAY_BEST_PAGE = '/every-day-best-page';
  static const MINE_COLLECT_PAGE = '/mine-collect-page';
  static const HOME_HOME_GAME_PAGE = '/home-game-page';
  static const HOME_HOME_POST_PAGE = '/home-post-page';
  static const POST_DETAILE_PAGE = '/post-detail-page';
  static const POST_TOPIC_PAGE = '/post-topic-page';
  static const TAG_DETAIL_PAGE = '/tag-detail-page';
  static const ACTIVITY_CENTER_PAGE = '/activity-center-page';
  static const ACTIVITY_WEB_PAGE = '/activity-web-page';
  static const WITHDRAW_CASH_BANK = '/withdraw-cash-bank';
  static const ENTER_GAME_WEB_VIEW = '/enter_game_web_view';
  static const BINDING_BANK_CARD = '/binding-bank-card';
  static const SHORT_VIDEO_PLAYER = '/short-video-player';
  static const INVITED_PAGE = '/invited-page';
  static const GAME_DETAILS_PAGE = '/game-details-page';
  static const COMIC_DETAIL_PAGE = '/comic-detail-page';
  static const COMIC_READER_PAGE = '/comic-reader-page';
  static const NOVEL_DETAIL_PAGE = '/novel-detail-page';
  static const NOVEL_READER_PAGE = '/novel-reader-page';
  static const CATEGORY_DETAIL_PAGE = '/category-detail-page';
  static const BOOK_STORE_PAGE = '/book-store-page';
  static const RANK_LIST_PAGE = '/rank-list-page';
  static const EPISODE_PREVIEW_PAGE = '/episode-preview-page';
  static const COMIC_WISHED_PAGE = '/comic-wished-page';
  static const WISHED_ACTIVE_PAGE = '/wished-active_page';
  static const WISHING_PAGE = "/wshing-page";
  static const BOOK_SHELF_PAGE = '/book-shelf-page';
  static const WATCH_HISTORY_PAGE = '/watch-history-page';
  static const REWARD_HISTORY_PAGE = '/reward-history-page';
  static const AI_CHANGE_FACE_PAGE = '/ai-change-face-page';
  static const AI_TASK_LIST_PAGE = '/ai-task-list-page';
  static const PREVIEW_IMAGE_VIEWER = '/preview-image-viewer';
  static const MY_CACHE_PAAGE = '/my-cache-paage';
  static const MY_CACHE_PAGE = '/my-cache-page';
  static const AI_RECOMMEND_PAGE = '/ai-recommend-page';
}
